version: '2'

services:
  app:
    image: ruby:2.6.3
    command: "sh startup.sh"
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PASSWORD=password
      - DATABASE_USER=root
      - DATABASE_URL=postgres://root:password@postgres/example
    working_dir: /project
    volumes:
      - .:/project
    ports:
     - 3000:3000
    links:
     - postgres

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=root
      - POSTGRES_DB=example
    ports:
      - 5432:5432
